// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpic0N0FfLBHbbo_dezv-lKFJIulPpAlM',
    appId: '1:51908180369:web:955630ced26113fa344230',
    messagingSenderId: '51908180369',
    projectId: 'tasks-c8da2',
    authDomain: 'tasks-c8da2.firebaseapp.com',
    storageBucket: 'tasks-c8da2.firebasestorage.app',
    measurementId: 'G-N9GDQN83DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFihazpxV0k0ZWvu7ROxj2vtwWKflOmzU',
    appId: '1:51908180369:android:64e12870925bc5fc344230',
    messagingSenderId: '51908180369',
    projectId: 'tasks-c8da2',
    storageBucket: 'tasks-c8da2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8A6txxV1R6QrdDpWqDLNOmDKGWdufxME',
    appId: '1:51908180369:ios:6d734969c29f39fa344230',
    messagingSenderId: '51908180369',
    projectId: 'tasks-c8da2',
    storageBucket: 'tasks-c8da2.firebasestorage.app',
    iosBundleId: 'com.example.crudTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8A6txxV1R6QrdDpWqDLNOmDKGWdufxME',
    appId: '1:51908180369:ios:6d734969c29f39fa344230',
    messagingSenderId: '51908180369',
    projectId: 'tasks-c8da2',
    storageBucket: 'tasks-c8da2.firebasestorage.app',
    iosBundleId: 'com.example.crudTodo',
  );
}
